# Generated by Django 5.2.8 on 2025-11-22 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('DEMANDE_RECUE', 'Nouvelle demande reçue'), ('DEMANDE_TRAITEE', 'Demande traitée'), ('LOCATION_DEMANDEE', 'Nouvelle demande de location'), ('LOCATION_CONFIRMEE', 'Location confirmée'), ('LOCATION_REFUSEE', 'Location refusée'), ('LOCATION_DEPART', 'Départ du véhicule'), ('LOCATION_RETOUR', 'Retour du véhicule'), ('LOCATION_RETARD', 'Retard de retour'), ('AVIS_RECU', 'Nouvel avis reçu'), ('AVIS_REPONSE', 'Réponse à votre avis'), ('COMPTE_VALIDE', 'Compte validé'), ('COMPTE_REJETE', 'Compte rejeté'), ('COMPTE_SUSPENDU', 'Compte suspendu'), ('FAVORI_PRIX_BAISSE', "Prix d'un favori a baissé"), ('FAVORI_DISPONIBLE', 'Favori disponible'), ('INFORMATION', 'Information'), ('ALERTE', 'Alerte'), ('ERREUR', 'Erreur')], max_length=50, verbose_name='Type de notification')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('niveau_priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=20, verbose_name='Niveau de priorité')),
                ('lien', models.CharField(blank=True, help_text='URL relative ou absolue', max_length=500, verbose_name='Lien vers une page')),
                ('texte_action', models.CharField(blank=True, help_text='Ex: Voir la demande, Consulter le véhicule', max_length=100, verbose_name="Texte du bouton d'action")),
                ('donnees_supplementaires', models.JSONField(blank=True, default=dict, help_text='Informations additionnelles en JSON', verbose_name='Données supplémentaires')),
                ('est_lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_expiration', models.DateTimeField(blank=True, help_text='Notification expirée après cette date', null=True, verbose_name="Date d'expiration")),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['destinataire', 'est_lue', 'date_creation'], name='notificatio_destina_85316d_idx'), models.Index(fields=['type_notification'], name='notificatio_type_no_ba8ea8_idx'), models.Index(fields=['niveau_priorite'], name='notificatio_niveau__f6fd53_idx')],
            },
        ),
    ]
