# Generated by Django 5.2.8 on 2025-11-23 13:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concessions', '0001_initial'),
        ('locations', '0002_location_code_promo_utilise_and_more'),
        ('vehicules', '0002_remove_vehicule_image_principale_photo_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la promotion')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('code', models.CharField(help_text='Code à saisir par le client (ex: SUMMER2024)', max_length=50, unique=True, verbose_name='Code promo')),
                ('type_reduction', models.CharField(choices=[('POURCENTAGE', 'Réduction en pourcentage'), ('MONTANT_FIXE', 'Réduction montant fixe')], default='POURCENTAGE', max_length=20, verbose_name='Type de réduction')),
                ('valeur_reduction', models.DecimalField(decimal_places=2, help_text='Pourcentage (0-100) ou montant fixe en FCFA', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valeur de la réduction')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('EXPIRE', 'Expiré')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('nombre_utilisations_max', models.PositiveIntegerField(blank=True, help_text='Laisser vide pour illimité', null=True, verbose_name="Nombre d'utilisations max (global)")),
                ('utilisations_par_client', models.PositiveIntegerField(default=1, verbose_name='Utilisations max par client')),
                ('nombre_utilisations', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisations actuelles")),
                ('montant_minimum', models.DecimalField(blank=True, decimal_places=2, help_text='Montant minimum de location pour appliquer la promo', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant minimum (FCFA)')),
                ('reduction_maximum', models.DecimalField(blank=True, decimal_places=2, help_text='Plafond de réduction (pour les pourcentages)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Réduction maximum (FCFA)')),
                ('est_cumulable', models.BooleanField(default=False, verbose_name="Cumulable avec d'autres promotions")),
                ('est_visible', models.BooleanField(default=True, help_text='Si désactivé, le code doit être saisi manuellement', verbose_name='Visible publiquement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('categories', models.ManyToManyField(blank=True, help_text='Laisser vide pour toutes les catégories', related_name='promotions', to='vehicules.categorie', verbose_name='Catégories ciblées')),
                ('clients_cibles', models.ManyToManyField(blank=True, help_text='Laisser vide pour tous les clients', limit_choices_to={'type_utilisateur': 'CLIENT'}, related_name='promotions_reservees', to=settings.AUTH_USER_MODEL, verbose_name='Clients ciblés (VIP)')),
                ('concession', models.ForeignKey(blank=True, help_text='Laisser vide pour toutes les concessions du concessionnaire', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='concessions.concession', verbose_name='Concession ciblée')),
                ('concessionnaire', models.ForeignKey(limit_choices_to={'type_utilisateur': 'CONCESSIONNAIRE'}, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_creees', to=settings.AUTH_USER_MODEL, verbose_name='Concessionnaire')),
                ('vehicules', models.ManyToManyField(blank=True, help_text='Laisser vide pour tous les véhicules', related_name='promotions', to='vehicules.vehicule', verbose_name='Véhicules ciblés')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='UtilisationPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_reduction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant de la réduction (FCFA)')),
                ('date_utilisation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'utilisation")),
                ('client', models.ForeignKey(limit_choices_to={'type_utilisateur': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_utilisees', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_appliquees', to='locations.location', verbose_name='Location associée')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations', to='promotions.promotion', verbose_name='Promotion')),
            ],
            options={
                'verbose_name': 'Utilisation de promotion',
                'verbose_name_plural': 'Utilisations de promotions',
                'ordering': ['-date_utilisation'],
            },
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['code'], name='promotions__code_e9f529_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['statut', 'date_debut', 'date_fin'], name='promotions__statut_329e66_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['concessionnaire'], name='promotions__concess_a9e29c_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisationpromotion',
            index=models.Index(fields=['promotion', 'client'], name='promotions__promoti_78db07_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisationpromotion',
            index=models.Index(fields=['date_utilisation'], name='promotions__date_ut_10b8f7_idx'),
        ),
    ]
