# Generated by Django 5.2.8 on 2025-11-17 12:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name="Nom de l'équipement")),
                ('icone', models.CharField(blank=True, help_text='Ex: 🎵 ou fa-music', max_length=50, verbose_name='Icône (classe CSS ou emoji)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('est_populaire', models.BooleanField(default=False, help_text='Afficher en priorité dans les filtres', verbose_name='Équipement populaire')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['-est_populaire', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(help_text='Ex: Toyota, Mercedes, Peugeot', max_length=100, verbose_name='Marque')),
                ('modele', models.CharField(help_text='Ex: Corolla, Classe C, 308', max_length=100, verbose_name='Modèle')),
                ('annee', models.IntegerField(help_text='Année de fabrication', validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)], verbose_name='Année')),
                ('type_vehicule', models.CharField(choices=[('BERLINE', 'Berline'), ('SUV', 'SUV'), ('4X4', '4x4'), ('CITADINE', 'Citadine'), ('BREAK', 'Break'), ('COUPE', 'Coupé'), ('MONOSPACE', 'Monospace'), ('UTILITAIRE', 'Utilitaire'), ('PICK_UP', 'Pick-up'), ('SPORTIVE', 'Sportive')], max_length=50, verbose_name='Type de véhicule')),
                ('type_carburant', models.CharField(choices=[('ESSENCE', 'Essence'), ('DIESEL', 'Diesel'), ('HYBRIDE', 'Hybride'), ('ELECTRIQUE', 'Électrique'), ('GAZ', 'Gaz (GPL/GNV)')], max_length=20, verbose_name='Type de carburant')),
                ('transmission', models.CharField(choices=[('MANUELLE', 'Manuelle'), ('AUTOMATIQUE', 'Automatique'), ('SEMI_AUTO', 'Semi-automatique')], max_length=20, verbose_name='Type de transmission')),
                ('nombre_places', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Nombre de places')),
                ('nombre_portes', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)], verbose_name='Nombre de portes')),
                ('climatisation', models.BooleanField(default=True, verbose_name='Climatisation')),
                ('kilometrage', models.IntegerField(help_text='En kilomètres', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kilométrage')),
                ('couleur', models.CharField(max_length=50, verbose_name='Couleur')),
                ('immatriculation', models.CharField(max_length=20, unique=True, verbose_name="Numéro d'immatriculation")),
                ('prix_jour', models.DecimalField(decimal_places=2, help_text='Tarif de location journalier', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix par jour (FCFA)')),
                ('caution', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant de la caution (FCFA)')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('equipements', models.JSONField(blank=True, default=list, help_text='Liste des équipements du véhicule (GPS, Bluetooth, etc.)', verbose_name='Équipements')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('LOUE', 'Loué'), ('MAINTENANCE', 'En maintenance'), ('INDISPONIBLE', 'Indisponible')], default='DISPONIBLE', max_length=20, verbose_name='Statut')),
                ('est_disponible', models.BooleanField(default=True, verbose_name='Disponible à la location')),
                ('image_principale', models.ImageField(help_text='Photo principale du véhicule', upload_to='vehicules/', verbose_name='Image principale')),
                ('nombre_locations', models.IntegerField(default=0, help_text='Nombre total de fois où le véhicule a été loué', verbose_name='Nombre de locations')),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note moyenne')),
                ('nombre_avis', models.IntegerField(default=0, verbose_name="Nombre d'avis")),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('derniere_maintenance', models.DateField(blank=True, null=True, verbose_name='Date de dernière maintenance')),
                ('prochaine_maintenance', models.DateField(blank=True, null=True, verbose_name='Date de prochaine maintenance')),
                ('concessionnaire', models.ForeignKey(limit_choices_to={'type_utilisateur': 'CONCESSIONNAIRE'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to=settings.AUTH_USER_MODEL, verbose_name='Concessionnaire propriétaire')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ImageVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicules/galerie/', verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name="Description de l'image")),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicules.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Image de véhicule',
                'verbose_name_plural': 'Images de véhicules',
                'ordering': ['ordre', '-date_ajout'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['marque', 'modele'], name='vehicules_v_marque_f101fd_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['statut', 'est_disponible'], name='vehicules_v_statut_0f787b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['prix_jour'], name='vehicules_v_prix_jo_ded1e5_idx'),
        ),
    ]
