# Generated by Django 5.2.8 on 2025-11-21 12:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_active', models.BooleanField(default=True)),
                ('nombre_vehicules', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
                'indexes': [models.Index(fields=['slug'], name='vehicules_c_slug_2cf5e6_idx'), models.Index(fields=['est_active'], name='vehicules_c_est_act_079851_idx')],
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Toyota, Mercedes, Peugeot', max_length=100, unique=True, verbose_name='Nom de la marque')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marques/logos/', verbose_name='Logo de la marque')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('pays_origine', models.CharField(blank=True, max_length=100, verbose_name="Pays d'origine")),
                ('site_web', models.URLField(blank=True, verbose_name='Site web officiel')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_active', models.BooleanField(default=True)),
                ('nombre_vehicules', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['nom'], name='vehicules_m_nom_3a7bad_idx'), models.Index(fields=['est_active'], name='vehicules_m_est_act_63faee_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modele', models.CharField(max_length=100)),
                ('annee', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)])),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('couleur', models.CharField(max_length=50)),
                ('type_carburant', models.CharField(choices=[('ESSENCE', 'Essence'), ('DIESEL', 'Diesel'), ('HYBRIDE', 'Hybride'), ('ELECTRIQUE', 'Électrique'), ('GAZ', 'Gaz (GPL/GNV)')], default='ESSENCE', max_length=20)),
                ('transmission', models.CharField(choices=[('MANUELLE', 'Manuelle'), ('AUTOMATIQUE', 'Automatique'), ('SEMI_AUTO', 'Semi-automatique')], default='MANUELLE', max_length=20)),
                ('nombre_places', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(50)])),
                ('nombre_portes', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)])),
                ('climatisation', models.BooleanField(default=True)),
                ('kilometrage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('puissance_fiscale', models.IntegerField(blank=True, null=True)),
                ('cylindree', models.IntegerField(blank=True, null=True)),
                ('est_disponible_vente', models.BooleanField(default=False)),
                ('est_disponible_location', models.BooleanField(default=True)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_location_jour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(5000)])),
                ('caution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('equipements', models.JSONField(blank=True, default=list)),
                ('image_principale', models.ImageField(upload_to='vehicules/principales/')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('LOUE', 'Loué'), ('MAINTENANCE', 'En maintenance'), ('INDISPONIBLE', 'Indisponible')], default='DISPONIBLE', max_length=20)),
                ('est_visible', models.BooleanField(default=True)),
                ('derniere_maintenance', models.DateField(blank=True, null=True)),
                ('prochaine_maintenance', models.DateField(blank=True, null=True)),
                ('nombre_vues', models.IntegerField(default=0)),
                ('nombre_locations', models.IntegerField(default=0)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('nombre_avis', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicules', to='vehicules.categorie')),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='concessions.concession')),
                ('concessionnaire', models.ForeignKey(limit_choices_to={'type_utilisateur': 'CONCESSIONNAIRE'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to=settings.AUTH_USER_MODEL)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicules', to='vehicules.marque')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ImageVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicules/galerie/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicules.vehicule')),
            ],
            options={
                'verbose_name': 'Image de véhicule',
                'verbose_name_plural': 'Images de véhicules',
                'ordering': ['ordre', '-date_ajout'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['marque', 'nom_modele'], name='vehicules_v_marque__e30b30_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['categorie', 'statut'], name='vehicules_v_categor_d481a9_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['concession', 'statut'], name='vehicules_v_concess_6fdd38_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['statut', 'est_visible'], name='vehicules_v_statut_27df08_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['prix_location_jour'], name='vehicules_v_prix_lo_d4d7be_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['immatriculation'], name='vehicules_v_immatri_698f22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicule',
            unique_together={('concessionnaire', 'immatriculation')},
        ),
    ]
