# Generated by Django 5.2.8 on 2025-11-18 20:08

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehicule',
            name='vehicules_v_statut_0f787b_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicule',
            name='vehicules_v_prix_jo_ded1e5_idx',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='est_disponible',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='prix_jour',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='est_disponible_location',
            field=models.BooleanField(default=False, verbose_name='Disponible à la location'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='est_disponible_vente',
            field=models.BooleanField(default=False, verbose_name='Disponible à la vente'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='prix_location_jour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarif de location journalier', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix par jour (FCFA)'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='prix_vente',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide si véhicule non disponible à la vente', max_digits=12, null=True, verbose_name='Prix de vente (FCFA)'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='caution',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant de la caution (FCFA)'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['statut', 'est_disponible_vente'], name='vehicules_v_statut_56026a_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['statut', 'est_disponible_location'], name='vehicules_v_statut_06f0e9_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['prix_location_jour'], name='vehicules_v_prix_lo_d4d7be_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['prix_vente'], name='vehicules_v_prix_ve_345934_idx'),
        ),
    ]
