# Generated by Django 5.2.8 on 2025-11-21 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='image_principale',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicules/photos/', verbose_name='Photo')),
                ('legende', models.CharField(blank=True, help_text='Description de la photo', max_length=200, verbose_name='Légende')),
                ('ordre', models.IntegerField(default=0, help_text='Plus le nombre est petit, plus la photo sera affichée en premier', verbose_name="Ordre d'affichage")),
                ('est_principale', models.BooleanField(default=False, help_text='Une seule photo principale par véhicule', verbose_name='Photo principale')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vehicules.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-est_principale', 'ordre', '-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_video', models.CharField(choices=[('UPLOAD', 'Fichier uploadé'), ('YOUTUBE', 'Lien YouTube'), ('VIMEO', 'Lien Vimeo'), ('AUTRE', 'Autre URL')], default='UPLOAD', max_length=20, verbose_name='Type de vidéo')),
                ('fichier', models.FileField(blank=True, help_text='Format accepté: MP4, WebM (max 100 MB)', null=True, upload_to='vehicules/videos/', verbose_name='Fichier vidéo')),
                ('url', models.URLField(blank=True, help_text='Lien YouTube, Vimeo, etc.', verbose_name='URL de la vidéo')),
                ('thumbnail', models.ImageField(blank=True, help_text="Image d'aperçu de la vidéo", null=True, upload_to='vehicules/videos/thumbnails/', verbose_name='Miniature')),
                ('titre', models.CharField(blank=True, help_text='Titre de la vidéo', max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duree', models.IntegerField(blank=True, help_text='Durée de la vidéo en secondes', null=True, verbose_name='Durée (secondes)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('nombre_vues', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='vehicules.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['ordre', '-date_ajout'],
            },
        ),
        migrations.DeleteModel(
            name='ImageVehicule',
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['vehicule', 'est_principale'], name='vehicules_p_vehicul_9d95a7_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['ordre'], name='vehicules_p_ordre_ab29b5_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['vehicule', 'type_video'], name='vehicules_v_vehicul_ef8794_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['ordre'], name='vehicules_v_ordre_0f4f51_idx'),
        ),
    ]
