# Generated by Django 5.2.8 on 2025-11-20 15:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Dakar, Thiès, Saint-Louis', max_length=100, unique=True, verbose_name='Nom de la région')),
                ('code', models.CharField(help_text='Code ISO ou administratif de la région', max_length=10, unique=True, verbose_name='Code région')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Coordonnée GPS centrale de la région', max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Coordonnée GPS centrale de la région', max_digits=10, null=True, verbose_name='Longitude')),
                ('nombre_concessions', models.IntegerField(default=0, help_text='Nombre de concessions dans cette région', verbose_name='Nombre de concessions')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['nom'], name='concessions_nom_eca3c7_idx'), models.Index(fields=['code'], name='concessions_code_85a984_idx')],
            },
        ),
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom commercial de la concession', max_length=200, verbose_name='Nom de la concession')),
                ('description', models.TextField(help_text='Description détaillée de la concession et de ses services', verbose_name='Description')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse complète')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('telephone', models.CharField(help_text='Format: +221XXXXXXXXX', max_length=15, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format: +221XXXXXXXXX', regex='^\\+221[0-9]{9}$')], verbose_name='Téléphone')),
                ('telephone_secondaire', models.CharField(blank=True, help_text='Format: +221XXXXXXXXX', max_length=15, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format: +221XXXXXXXXX', regex='^\\+221[0-9]{9}$')], verbose_name='Téléphone secondaire')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Coordonnée GPS (ex: 14.7167)', max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Coordonnée GPS (ex: -17.4677)', max_digits=10, verbose_name='Longitude')),
                ('horaires', models.JSONField(default=dict, help_text="Format JSON: {'lundi': {'ouvert': true, 'debut': '08:00', 'fin': '18:00'}, ...}", verbose_name="Horaires d'ouverture")),
                ('ouvert_weekend', models.BooleanField(default=False, verbose_name='Ouvert le weekend')),
                ('services', models.JSONField(default=list, help_text='Liste des services (Vente, Location, Entretien, Réparation, etc.)', verbose_name='Services proposés')),
                ('numero_registre_commerce', models.CharField(help_text="NINEA ou numéro d'immatriculation", max_length=50, unique=True, verbose_name='Numéro de registre de commerce')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='concessions/logos/', verbose_name='Logo de la concession')),
                ('photo_facade', models.ImageField(blank=True, null=True, upload_to='concessions/facades/', verbose_name='Photo de la façade')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé et actif'), ('SUSPENDU', 'Suspendu temporairement'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('raison_rejet', models.TextField(blank=True, help_text='Explication si la concession est rejetée', verbose_name='Raison du rejet')),
                ('nombre_vehicules', models.IntegerField(default=0, help_text='Nombre total de véhicules dans cette concession', verbose_name='Nombre de véhicules')),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note moyenne')),
                ('nombre_avis', models.IntegerField(default=0, verbose_name="Nombre d'avis")),
                ('nombre_vues', models.IntegerField(default=0, help_text='Nombre de fois où la fiche a été consultée', verbose_name='Nombre de vues')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('est_visible', models.BooleanField(default=True, help_text='Permet de masquer temporairement la concession', verbose_name='Visible sur la plateforme')),
                ('concessionnaire', models.ForeignKey(limit_choices_to={'type_utilisateur': 'CONCESSIONNAIRE'}, on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to=settings.AUTH_USER_MODEL, verbose_name='Concessionnaire propriétaire')),
                ('validee_par', models.ForeignKey(blank=True, limit_choices_to={'type_utilisateur': 'ADMINISTRATEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concessions_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concessions', to='concessions.region', verbose_name='Région')),
            ],
            options={
                'verbose_name': 'Concession',
                'verbose_name_plural': 'Concessions',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['concessionnaire', 'statut'], name='concessions_concess_e5caf5_idx'), models.Index(fields=['region', 'statut'], name='concessions_region__feadce_idx'), models.Index(fields=['ville'], name='concessions_ville_16ff76_idx'), models.Index(fields=['statut', 'est_visible'], name='concessions_statut_f53889_idx'), models.Index(fields=['latitude', 'longitude'], name='concessions_latitud_23e741_idx')],
                'unique_together': {('concessionnaire', 'nom')},
            },
        ),
    ]
