# Generated by Django 5.2.8 on 2025-11-21 15:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concessions', '0001_initial'),
        ('vehicules', '0002_remove_vehicule_image_principale_photo_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début prévue')),
                ('date_fin', models.DateField(verbose_name='Date de fin prévue')),
                ('date_depart_reel', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de départ réel')),
                ('date_retour_reel', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de retour réel')),
                ('prix_jour', models.DecimalField(decimal_places=2, help_text='Prix journalier au moment de la réservation', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix par jour (FCFA)')),
                ('nombre_jours', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de jours prévus')),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix total (FCFA)')),
                ('caution', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant de la caution (FCFA)')),
                ('kilometrage_depart', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kilométrage au départ')),
                ('kilometrage_retour', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kilométrage au retour')),
                ('statut', models.CharField(choices=[('DEMANDE', 'Demande en attente'), ('CONFIRMEE', 'Confirmée par le concessionnaire'), ('EN_COURS', 'En cours (véhicule parti)'), ('TERMINEE', 'Terminée (véhicule retourné)'), ('ANNULEE', 'Annulée')], default='DEMANDE', max_length=20, verbose_name='Statut de la location')),
                ('jours_retard', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de jours de retard')),
                ('montant_penalite', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant des pénalités (FCFA)')),
                ('taux_penalite_jour', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Pourcentage du prix journalier appliqué en pénalité par jour de retard', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taux pénalité par jour (%)')),
                ('notes_client', models.TextField(blank=True, help_text='Remarques ou demandes particulières du client', verbose_name='Notes du client')),
                ('notes_concessionnaire', models.TextField(blank=True, help_text='Notes internes du concessionnaire', verbose_name='Notes du concessionnaire')),
                ('etat_depart', models.TextField(blank=True, help_text="Description de l'état du véhicule au moment du départ", verbose_name='État du véhicule au départ')),
                ('etat_retour', models.TextField(blank=True, help_text="Description de l'état du véhicule au moment du retour", verbose_name='État du véhicule au retour')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création de la demande')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('client', models.ForeignKey(limit_choices_to={'type_utilisateur': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='concessions.concession', verbose_name='Concession')),
                ('concessionnaire', models.ForeignKey(limit_choices_to={'type_utilisateur': 'CONCESSIONNAIRE'}, on_delete=django.db.models.deletion.CASCADE, related_name='locations_gerees', to=settings.AUTH_USER_MODEL, verbose_name='Concessionnaire gestionnaire')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='vehicules.vehicule', verbose_name='Véhicule loué')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ContratLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(help_text='Format: CONT-YYYYMMDD-XXXXX', max_length=50, unique=True, verbose_name='Numéro du contrat')),
                ('fichier_pdf', models.FileField(upload_to='contrats/locations/%Y/%m/', verbose_name='Fichier PDF du contrat')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('hash_contrat', models.CharField(blank=True, help_text="Pour vérification d'intégrité", max_length=64, verbose_name='Hash SHA256 du contrat')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='locations.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Contrat de location',
                'verbose_name_plural': 'Contrats de location',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['client', 'statut'], name='locations_l_client__45387a_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['vehicule', 'statut'], name='locations_l_vehicul_30fe95_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['concessionnaire', 'statut'], name='locations_l_concess_e8a72c_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['date_debut', 'date_fin'], name='locations_l_date_de_5784c7_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['statut', 'date_creation'], name='locations_l_statut_b2a1ed_idx'),
        ),
    ]
