# Generated by Django 5.2.8 on 2025-11-23 13:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='code_promo_utilise',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code promo utilisé'),
        ),
        migrations.AddField(
            model_name='location',
            name='montant_reduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant de la réduction (FCFA)'),
        ),
        migrations.AddField(
            model_name='location',
            name='prix_avant_reduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix avant réduction (FCFA)'),
        ),
    ]
