# Generated by Django 5.2.8 on 2025-11-23 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_code_promo_utilise_and_more'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='promotions.promotion', verbose_name='Promotion appliquée'),
        ),
    ]
