# Generated by Django 5.2.8 on 2025-11-21 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicules', '0002_remove_vehicule_image_principale_photo_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('CONTACT', 'Demande de contact'), ('ESSAI', "Demande d'essai"), ('DEVIS', 'Demande de devis'), ('INFORMATION', "Demande d'information")], default='CONTACT', max_length=20, verbose_name='Type de demande')),
                ('objet', models.CharField(help_text='Résumé court de la demande', max_length=200, verbose_name='Objet de la demande')),
                ('message', models.TextField(help_text='Description détaillée de la demande', verbose_name='Message du client')),
                ('date_souhaitee_essai', models.DateField(blank=True, null=True, verbose_name="Date souhaitée pour l'essai")),
                ('heure_souhaitee_essai', models.TimeField(blank=True, null=True, verbose_name="Heure souhaitée pour l'essai")),
                ('telephone_contact', models.CharField(max_length=15, verbose_name='Téléphone de contact')),
                ('email_contact', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de traitement'), ('EN_COURS', 'En cours de traitement'), ('TRAITEE', 'Traitée'), ('ANNULEE', 'Annulée par le client')], default='EN_ATTENTE', max_length=20, verbose_name='Statut de la demande')),
                ('reponse', models.TextField(blank=True, null=True, verbose_name='Réponse du concessionnaire')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de la réponse')),
                ('notes_internes', models.TextField(blank=True, help_text='Notes visibles uniquement par le concessionnaire', verbose_name='Notes internes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('client', models.ForeignKey(limit_choices_to={'type_utilisateur': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Client demandeur')),
                ('concessionnaire', models.ForeignKey(limit_choices_to={'type_utilisateur': 'CONCESSIONNAIRE'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_recues', to=settings.AUTH_USER_MODEL, verbose_name='Concessionnaire destinataire')),
                ('repondu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_repondues', to=settings.AUTH_USER_MODEL, verbose_name='Répondu par')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='vehicules.vehicule', verbose_name='Véhicule concerné')),
            ],
            options={
                'verbose_name': 'Demande de contact',
                'verbose_name_plural': 'Demandes de contact',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['client', 'statut'], name='demands_dem_client__d423d8_idx'), models.Index(fields=['concessionnaire', 'statut'], name='demands_dem_concess_9dfcc5_idx'), models.Index(fields=['vehicule', 'statut'], name='demands_dem_vehicul_dd7564_idx'), models.Index(fields=['type_demande', 'statut'], name='demands_dem_type_de_518f8e_idx'), models.Index(fields=['date_creation'], name='demands_dem_date_cr_017268_idx')],
            },
        ),
    ]
