# Generated by Django 5.2.8 on 2025-11-21 20:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('vehicules', '0002_remove_vehicule_image_principale_photo_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(help_text='Note de 1 (très mauvais) à 5 (excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1-5 étoiles)')),
                ('note_confort', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note confort')),
                ('note_performance', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note performance')),
                ('note_consommation', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note consommation')),
                ('note_proprete', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note propreté')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'avis")),
                ('commentaire', models.TextField(verbose_name='Commentaire détaillé')),
                ('points_positifs', models.TextField(blank=True, help_text='Ce qui a plu au client', verbose_name='Points positifs')),
                ('points_negatifs', models.TextField(blank=True, help_text='Ce qui pourrait être amélioré', verbose_name='Points négatifs')),
                ('recommande', models.BooleanField(default=True, help_text='Le client recommande-t-il ce véhicule ?', verbose_name='Recommande ce véhicule')),
                ('reponse', models.TextField(blank=True, verbose_name='Réponse du concessionnaire')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de la réponse')),
                ('est_valide', models.BooleanField(default=True, help_text='Validé par la modération', verbose_name='Avis validé')),
                ('est_signale', models.BooleanField(default=False, help_text='Signalé comme inapproprié', verbose_name='Avis signalé')),
                ('raison_signalement', models.TextField(blank=True, verbose_name='Raison du signalement')),
                ('date_moderation', models.DateTimeField(blank=True, null=True, verbose_name='Date de modération')),
                ('nb_personnes_utile', models.IntegerField(default=0, verbose_name='Nombre de personnes trouvant cet avis utile')),
                ('nb_personnes_inutile', models.IntegerField(default=0, verbose_name='Nombre de personnes trouvant cet avis inutile')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('client', models.ForeignKey(limit_choices_to={'type_utilisateur': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('location', models.OneToOneField(help_text='Avis basé sur cette location', on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='locations.location', verbose_name='Location associée')),
                ('modere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_moderes', to=settings.AUTH_USER_MODEL, verbose_name='Modéré par')),
                ('repondu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_repondus', to=settings.AUTH_USER_MODEL, verbose_name='Répondu par')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='vehicules.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['vehicule', 'est_valide'], name='avis_avis_vehicul_42f832_idx'), models.Index(fields=['client'], name='avis_avis_client__97828f_idx'), models.Index(fields=['note'], name='avis_avis_note_b68d14_idx'), models.Index(fields=['date_creation'], name='avis_avis_date_cr_03ddde_idx'), models.Index(fields=['est_signale'], name='avis_avis_est_sig_3babfc_idx')],
                'unique_together': {('client', 'location')},
            },
        ),
    ]
