# Generated by Django 5.2.8 on 2025-11-14 15:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('CLIENT', 'Client'), ('CONCESSIONNAIRE_PROPRIETAIRE', 'Concessionnaire - Propriétaire'), ('CONCESSIONNAIRE_GERANT', 'Concessionnaire - Gérant'), ('CONCESSIONNAIRE_EMPLOYE', 'Concessionnaire - Employé'), ('ADMINISTRATEUR_SUPER', 'Administrateur - Super Admin'), ('ADMINISTRATEUR_MODERATEUR', 'Administrateur - Modérateur')], max_length=100, unique=True, verbose_name='Nom du rôle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('peut_gerer_vehicules', models.BooleanField(default=False)),
                ('peut_gerer_concessions', models.BooleanField(default=False)),
                ('peut_gerer_utilisateurs', models.BooleanField(default=False)),
                ('peut_voir_statistiques', models.BooleanField(default=False)),
                ('peut_moderer_contenu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=150, verbose_name='Prénom')),
                ('telephone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Maximum 15 chiffres.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profils/', verbose_name='Photo de profil')),
                ('type_utilisateur', models.CharField(choices=[('CLIENT', 'Client'), ('CONCESSIONNAIRE', 'Concessionnaire'), ('ADMINISTRATEUR', 'Administrateur')], default='CLIENT', max_length=50, verbose_name="Type d'utilisateur")),
                ('preferences_notifications', models.JSONField(blank=True, default=dict, verbose_name='Préférences de notifications')),
                ('newsletter_acceptee', models.BooleanField(default=False, verbose_name='Newsletter acceptée')),
                ('nom_entreprise', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'entreprise")),
                ('siret', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='Le SIRET doit contenir exactement 14 chiffres', regex='^\\d{14}$')], verbose_name='SIRET')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('logo_entreprise', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name="Logo de l'entreprise")),
                ('description_entreprise', models.TextField(blank=True, verbose_name="Description de l'entreprise")),
                ('est_valide', models.BooleanField(default=False, verbose_name='Compte validé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('niveau_acces', models.CharField(blank=True, choices=[('SUPER', 'Super Administrateur'), ('MODERATEUR', 'Modérateur'), ('SUPPORT', 'Support Client')], max_length=50, verbose_name="Niveau d'accès")),
                ('peut_valider_concessionnaires', models.BooleanField(default=False, verbose_name='Peut valider les concessionnaires')),
                ('peut_supprimer_utilisateurs', models.BooleanField(default=False, verbose_name='Peut supprimer des utilisateurs')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='users.role', verbose_name='Rôle')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
