# Generated by Django 5.2.8 on 2025-11-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pourcentage_completion',
            field=models.IntegerField(default=0, help_text='Calculé automatiquement selon les champs remplis', verbose_name='Pourcentage de complétion du profil'),
        ),
        migrations.AddField(
            model_name='user',
            name='raison_rejet',
            field=models.TextField(blank=True, help_text="Raison pour laquelle le compte a été rejeté par l'administrateur", verbose_name='Raison du rejet'),
        ),
        migrations.AddField(
            model_name='user',
            name='statut_compte',
            field=models.CharField(choices=[('INCOMPLETE', 'Profil incomplet'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='INCOMPLETE', max_length=50, verbose_name='Statut du compte'),
        ),
    ]
