# Generated by Django 5.2.8 on 2025-11-22 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicules', '0002_remove_vehicule_image_principale_photo_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout aux favoris")),
                ('alerte_prix_active', models.BooleanField(default=False, help_text='Notifier si le prix baisse', verbose_name='Alerte prix activée')),
                ('prix_initial', models.DecimalField(blank=True, decimal_places=2, help_text="Prix au moment de l'ajout aux favoris", max_digits=12, null=True, verbose_name='Prix initial (FCFA)')),
                ('notes', models.TextField(blank=True, help_text='Notes du client sur ce véhicule', verbose_name='Notes personnelles')),
                ('client', models.ForeignKey(limit_choices_to={'type_utilisateur': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='vehicules.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-date_ajout'],
                'indexes': [models.Index(fields=['client', 'date_ajout'], name='favoris_fav_client__9fdce4_idx'), models.Index(fields=['vehicule'], name='favoris_fav_vehicul_455934_idx')],
                'unique_together': {('client', 'vehicule')},
            },
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('MAJ_PROFIL', 'Mise à jour du profil'), ('CHANGE_PASSWORD', 'Changement de mot de passe'), ('CONSULTATION_VEHICULE', "Consultation d'un véhicule"), ('AJOUT_FAVORI', 'Ajout aux favoris'), ('RETRAIT_FAVORI', 'Retrait des favoris'), ('DEMANDE_CONTACT', 'Demande de contact'), ('DEMANDE_ESSAI', "Demande d'essai"), ('DEMANDE_DEVIS', 'Demande de devis'), ('DEMANDE_LOCATION', 'Demande de location'), ('LOCATION_CONFIRMEE', 'Location confirmée'), ('LOCATION_ANNULEE', 'Location annulée'), ('DEPART_VEHICULE', 'Départ du véhicule'), ('RETOUR_VEHICULE', 'Retour du véhicule'), ('AVIS_PUBLIE', 'Avis publié'), ('AVIS_MODIFIE', 'Avis modifié'), ('AJOUT_CONCESSION', "Ajout d'une concession"), ('MAJ_CONCESSION', "Mise à jour d'une concession"), ('AJOUT_VEHICULE', "Ajout d'un véhicule"), ('MAJ_VEHICULE', "Mise à jour d'un véhicule")], max_length=50, verbose_name="Type d'action")),
                ('description', models.TextField(blank=True, verbose_name="Description de l'action")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent (navigateur)')),
                ('donnees_supplementaires', models.JSONField(blank=True, default=dict, help_text='Informations additionnelles en JSON', verbose_name='Données supplémentaires')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique', to='vehicules.vehicule', verbose_name='Véhicule concerné')),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historique',
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['utilisateur', 'date_action'], name='favoris_his_utilisa_fead96_idx'), models.Index(fields=['type_action', 'date_action'], name='favoris_his_type_ac_be7077_idx'), models.Index(fields=['vehicule', 'date_action'], name='favoris_his_vehicul_39cb02_idx')],
            },
        ),
    ]
